# Generated by Django 3.2 on 2021-05-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('number', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('password1', models.CharField(max_length=122)),
                ('password2', models.CharField(max_length=122)),
            ],
            options={
                'db_table': 'projecthr',
            },
        ),
    ]
