# Generated by Django 3.2 on 2021-05-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_registration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='tes03',
        ),
    ]
