# Generated by Django 3.2 on 2021-05-07 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_registration_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration',
            new_name='Register',
        ),
    ]
