# Generated by Django 3.2 on 2021-05-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_registration_register'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='test',
        ),
    ]
