# Generated by Django 3.2 on 2021-05-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_register_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='register',
            table='test02',
        ),
    ]
