# Generated by Django 3.2 on 2021-05-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210508_1003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hrproject',
            table='projecthr',
        ),
    ]
