# Generated by Django 3.2 on 2021-05-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_hrproject_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hrproject',
            table='projecthr',
        ),
    ]
