# Generated by Django 3.2 on 2021-05-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_hrproject_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrproject',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='hrproject',
            old_name='password1',
            new_name='skills',
        ),
        migrations.RemoveField(
            model_name='hrproject',
            name='password2',
        ),
        migrations.AlterModelTable(
            name='hrproject',
            table='',
        ),
    ]
